function showAgentDescription(agentName) { // Funktsisoon agentide kirjelduste kuvamiseks nuppude kõrval oleval alal. Koodi kirjutas ChatGPT (https://chat.openai.com/).
  var descriptionElement = document.getElementById("agentKirjeldus");

  var agentDescriptions = {
    'Astra': 'Astra: \nRoll: Controller \nVõimed: \nAstra saab x-i vajutades minna Astral Formi, kus ta saab kaardile panna tähekesi. Astra saab maha pandud tähekesi tagasi võtta, tagasi võttes moodustab täht korraks suitsupilve. \nQ - Nova Pulse: valitud täht aktiveeritakse ja tähe raadiuses pulsiga pihta saanud tegelased liiguvad sihivad ja tulistavad lühikest aega aeglasemalt. \nE - Nebula: valitud täht aktiveerub, moodustades valitud kohta suitsupilve. \nC - Gravity Well: valitud täht hakkab mõneks sekundiks tegelasi tähe raadiuses tähe keskpunkti poole tõmbama. Kui keegi pole tähe sissetõmbamise aja lõpuks tähe raadiusest põgenenud on ta vigastused mõne sekundi jooksul topelt tugevad. \nX - Cosmic Divide: Astra saab Astral Formis olles parema klikiga maha panna punkti, mille abil ta seina vastavalt oma äranägemise järgi keerata saab uut punkti valides moodustub nende kahe punktiga määratud sirgele sein. Sein on kuulikindel ja sellest ei kostu hääled läbi.',
    'Breach': 'Breach: \nRoll: Initiator \nVõimed: \nQ - Aftershock: Breach valib koha seina taga, mida ta soovib rünnata, tekitades plahvatuse valitud kohas. \nE - Flashpoint: Breach viskab valitud objekti või nurga taha helendava laengu, mis plahvatades pimestab vaenlasi, kes seda näevad. \nC - Fault Line: Breach laseb maapinnale seismilise laine, aeglustamaks vaenlaste liikumist, sihtimist ja tulistamist. \nX - Rolling Thunder: Breach laseb maapinnale suure seismilise laine, mis aeglustab vaenlaste liikumist, sihtimist ja tulistamist ja viskab nad veidi kaugemale.',
    'Brimstone': 'Brimstone: \nRoll: Controller \nVõimed: \nQ - Incendiary: Võtab kätte granaadiheitja, mis vasakpoolse hiirevajutusega tulistab granaadi, mis põrandale kukkudes tööle hakkab, luues tuleala, mis kahjustab selle sees asuvaid mängijaid. \nE - Sky Smoke: Kasutades avaneb kaart, millele saab asetada vasaku hiirevajutusega suitsupilvi, mis parem klikiga käivituvad ja blokeerivad ära valitud osa mängu alast. \nC - Stim Beacon: Heidab välja ala, mille sees olles muutub liikumine kiiremaks ja tulistamise kiirus veidi suuremaks. \nX - Orbital Strike: Võtab kätte kaardi, millel saad valida koha kaardil, mida tabab hävitav laser, mis vigastab kõvasti inimesi selle sees.',
    'Chamber': 'Chamber: \nRoll: Sentinel \nVõimed: \nQ - Headhunter: Chamber võtab kätte tugeva püstoli, millel on ka parem sihik kaugemateks tulevahetusteks. Lask pähe on võimeline tapma igalt kauguselt. \n E - Rendezvous: Chamber võtab kätte seadeldise, mis maha pannes loob selle ümber raadiuse, milles olles Chamber saab uuesti e vajutusega koheselt teleporteeruda raadiuse keskpunkti ehk seadeldise peale. \nC - Trademark: Chamber võtab kätte lõksu, mis maha pannes valvab mingit ala mängus. Kui vastased sinna alale lähevad aeglustab lõks neid ja annab heliga Chamber-ile märku. \nX - Tour de Force: Aktiveerides võtab Chamber välja võimsa sniper rifle’i, mis tapab ühe lasuga ülakehasse pihta saanud vastase. Surma saanud vastase asukohale ilmub mõneks ajaks aeglustav väli.',
    'Cypher': 'Cypher: \nRoll: Sentinel \nVõimed: \nQ - Cyber Cage: Cypher paigaldab puuri, mis aktiveerimisel loob puuri, millest kui vastane läbi läheb, teeb häält ja kuulutab selle käivitumisest mängijatele. \nE - Spy Camera: Cypher paigaldab kaamera, mida saab vaadata, et jälgida vaenlase tegevust. Vasaku klikiga saab ta tulistada väikeseid nooli, mis tuvastab vastast läbi seinte, kuni ta selle enda küljest eemaldab. \nC - Trapwire: Cypher paneb lõksu, mis kinnitatakse kahele pinnale, luues nähtamatu Tripwire’i, mis mängija sissetuleku korral neid märgistavad ja aeglustavad. \nX - Neural Theft: Cypher saab surnud vastase juures paljastada kõigi vastaste asukohad kaardil ja ka mängus sees.',
    'Deadlock': 'Deadlock: \nRoll: Sentinel \nVõimed: \nQ - Sonic Sensor: Deadlock saab paigutada mängus erinevatele pindadele oma sensorid, mis heli kuuldes antud piirkonnas olevate mängijate sihtimise, liikumise ja tulistamise aeglaseks muudavavad. \nE - Barrier Mesh: Deadlock võtab kätte ketta, mida visates ilmub maandumiskohta x tähe kujul neli seina, millest läbi ei saa liikuda, kuid sellest saab läbi tulistada. Seinu saab ükshaaval hävitades tulistades x-i otstes olevadi pallikesi, ja seina saab korraga lõhkuda, tulistades seina x-i keskpunktis olevat suuremat pallikest. \nC - Gravnet: Deadlock võtab kätte granaadi, mis maad puutudes paneb kõik mängijad granaadi alas teatud ajaks kükitama. \nX - Annihilation: Deadlock võtab kätte relva, mis põrkab kuni ühelt seinalt ja millega pihta saades läheb vastane kookoni sisse ja ta lõmmatakse aeglaselt tulistuskoha poole, kuhu jõudes ta lõpuks sureb. Vastased saavad lõksu jäänud tiimikaaslase päästa tulistades kookonit.',
    'Fade': 'Fade: \nRoll: Initiator \nVõimed: \nQ - Seize: Fade võtab kätte palli, mis maandudes teeb nii, et vaenlased, kes selle raadiuses on jäävad kinni ega saa kera ringi keskpunkrist kuigi kaugele joosta. Samuti teeb see nad ajutiselt kurdiks. \nE - Haunt: Fade võtab kätte eluka, keda visates ilmub maandumiskohta elukas, kes paljastab kõigi seda elukat nägevate vastaste asukohad. \nC - Prowler: Fade võtab kätte eluka, kelle ta saab panna vasaku klikiga maha otse liikuma või vasaku hiirenupu hoidmisega saab Fade teda ka juhtida. Prowler lukustub vastase peale, kui ta teda mõnda näeb ja jälitab teda. Prowleriga pihta saades muutub vastase vaate- ja kuulmisväli väiksemaks. \nX - Nightfall: Fade saadab enda ette suure laine, mis märgistab ära vastased, kes sinna sisse jäid ja muudab nad kestvuse ajaks kurdiks.',
    'Gekko': 'Gekko: \nRoll: Initiator \nVõimed: \nQ - Wingman: Gekko võtab kätte Wingmani. Vasaku klikiga saadab Gekko Wingmani sirge trajektooriga vastaseid otsima. Leides vastase vallandab Wingman plahvatuse, mis aeglustab pihta saanud vastaste liikumist, sihtimist ja tulistamist. Kui Gekkol on Spike saab ta Wingmani paremklikiga saata Spike’i plantima ja kui Gekko näeb vastaste Spike’i saab ta Wingmani saata seda kahjutuks tegema. Wingmani saab uuesti üles korjata ja mitu korda kasutada. \nE - Dizzy: Gekko võtab kätte Dizzy, keda visates hakkab Dizzy korraks hõljuma ja pimestab kõik vastased keda ta näeb. Dizzy saab uuesti üles korjata ja mitu korda kasutada. \nC - Mosh Pit: Gekko võtab kätte Moshi ja saab teda parema klikiga nõrgalt ja vasaku klikiga tugevamini visata. Mosh paljuneb kiirelt maandutud alas ja peale mõnda sekundit plahvatab. \nX - Trash: Gekko võtab Trash’i kätte ja vasaku klikiga aktiveerib ta. Gekko juhib Trash’i ja saab temaga mängus ringi liikuda. Trash saab ringi liikudes hüpata kuskile poole ja kui Trash hüppab ja saab kellelegi pihta, ei saa pihta saanud mängijad enam mõningate sekundite jooksul midagi teha. Trash’i saab üles korjata ja mitu korda kasutada.',
    'Harbor': 'Harbor: \nRoll: Controller \nVõimed: \nQ - Cove: Võtab kätte kera, mis maandudes moodustab veemulli, mis blokeerib relvade kuule. Mulli saab katki tulistada, mulli saab parema klikiga nõrgemini visata ja vasaku klikiga tugevamin visata. \nE - High Tide: Harbor võtab kätte vee seina. Vasaku klikiga saadab Harbor seina otsejooneliselt edasi, vasakut hiireklahvi hoides saab harbor seina trajektoori suunata. Kõik, kes seinast läbi lähevad, aeglustuvad korraks. \nC -Cascade: Harbor võtab  kätte vaatamissuunaga risti oleva seina ja lükkab selle otse edasi. Seina saab peatada sobival hetkel ja vastavalt vajadusele pöörata. Mängijad, kes seinast läbi lähevad, aeglustuvad korraks. \nX - Reckoning: Harbor võtab kätte oma võime ja sihib seda. Vasaku klikiga muutub sihitud ala märjaks ja vastaste ümber, kes ala sees on, hakkavad iga mõne sekundi taga ilmuma geisrid. Kui vastased geisrist välja ei liigu, muutuvad nad aeglasemaks: sihivad, liiguvad ja tulistavad aeglasemini.',
    'ISO': 'ISO: \nRoll: Duelist \nVõimed: \nQ- Undercut: Võtab kätte võime, mida visates muutuvad vastased, keda see tabas, nõrgemaks ehk saavad kaks korda rohkem vigastada. Võime läheb kõigest läbi k.a seinad. \nE - Double Tap: Alustab fookuse taimerit. Kui see on lõppenud, siseneb ISO olekusse, mille ajal surevad vaenlased, keda sa tapad või kahjustad, genereerivad energiapalli. Selle palli tulistamine annab kilbi, mis nullib järgmise vigastuse. \nC - Contingency: ISO võtab kätte kuulikindla seina, mida kasutades liigub sein otse edasi. \nX - Kill Contract: Iso aktiveerib teatud alas areeni, alas esimene vastane võetakse kaasa ja toimub 1 vs 1 võitlus ISO ja vastase vahel. Võitja saab mängus edasi mängida, kaotaja sureb.',
    'Jett': 'Jett: \nRoll: Duelist \nVõimed: \nPassive: Hüppamist (tühikut) all hoides langeb/kukub Jett aeglasemalt. \nQ - Updraft: Jett hüppab kõrgele õhku, võimaldades ootamatut ja kiiret asukohavahetust ja kõrgemale liikumist. \nE - Tailwind: Jett liigub kiiresti edasi valitud suunas. \nC - Cloudburst: Jett viskab kerakujulise suitsupilve, mida saab hiirega veidi suunata, maandudes loob lühikeseks ajaks suitsupilve. \nX - Blade Storm: Jett võtab välja 5 nuga, mida saab liikumise pealt täpselt sihtida ja mis tapmise korral ilmuvad kõik tagasi.',
    'KAY/O': 'KAY/O: \nRoll: Initiator \nVõimed: \nQ- Flash/dive: KAY/O võtab kätte granaadi, mida saab parema klikiga nõrgemalt enda lähedale visata või vasaku klikiga tugevamini heita. Granaat pimestab plahvatades mõneks sekundiks kõiki, kes seda näevad. \nE - Zero/point: KAY/O võtab kätte noa, mis visates loob kera ja annab infot, kes kera alal on. Noa loodud kera sisse jäänud vastased ei saa oma võimeid mõni aeg kasutada. \nC - Frag/ment: KAY/O võtab kätte granaadi, mis visates kokkupuutel põrandaga loob ala, mis plahvatab neli korda lühikese aja jooksul. \nX - Null/cmd: KAY/O laskmiskiirus muutub kiiremaks ja ta hakkab eritama suure raadiusega pulsse, mis keelavad selles alas vastastel oma võimeid kasutada. Kui KAY/O sureb samal ajal, kui ta oma x-võimet kasutab saavad ta tiimikaaslased ta tagasi püsti aidata.',
    'Killjoy': 'Killjoy: \nRoll: Sentinel \nVõimed: \nQ- Alarmbot: Killjoy saab maha panna valveroboti, kes teatud ala valvab ja kui mõni vastane sinna alale satub jookeb robot tema poole, teavitades Killjoy’d ja tehes nii, et kätte saadud vastane kaotab viga saades topelt elusid. \nE - Turret: Killjoy saab paigutada sobivasse kohta roboti, kes mingit ala jälgima hakkb. Leides oma jälgitavast alast vastase hakkab robot teda tulistama. \nC - Nanoswarm: Killjoy saab visata, parema klikiga nõrgalt ja vasaku klikiga tugevamalt, granaadi, mis maandudes aktiveerub. Killjoy saab sobival ajal maandunud granaadi tööle panna, kahjustades granaadi mõjuraadiusesse jäänud mängijaid. \nX - Lockdown: Killjoy asetab sobivasse kohta mängus oma seadeldise, peale mida algab taimer, mille lõppedes jäävad kõik seadeldise märgistatud raadiuses olevad vastased kinni ega saa mõni aeg midagi teha.',
    'Neon': 'Neon: \nRoll: Duelist \nVõimed: \nQ - Relay Bolt: Viskab energiapalli, mis põrkab ühe korra ja tekitab maapinnale lühiajalise šoki. \nE - High Gear: Võimaldab Neonil relvad ära panna ja mängus kiiresti liikuda. Lisaks saab ta üllatada vastaseid põlvili libisemisega. \nC - Fast Lane: Loob kahe seinaga pika tunnel, millest pole läbi näha. \nX - Overdrive: Neon saab ajutiselt kiirema liikumiskiiruse ja ta sõrmeotstest hakkab tulema välja elektrit, millega ta saab vastaseid lasta, elektri kestus uuendatakse iga saadud tapmisega.',
    'Omen': 'Omen: \nRoll: Controller \nVõimed: \nQ - Shrouded Step: Omen saab teleporteeruda lühikese vahemaa taha valitud asukohta. \nE - Paranoia: Omen saadab laine, mis vähendab vaenlaste vaate- ja kuulmisvälja nii, et nad näevad ainult enda ette. \nC - Dark Cover: Omen saab paigutada mängus suitsupilvi, et blokeerida vaatevälju. \nX - From the Shadows: Omen võib valida kaardil koha, kuhu teleporteeruda, olenemata asukohast, kus ta seisab.',
    'Phoenix': 'Phoenix: \nRoll: Duelist \nVõimed: \nQ - Curveball: Võtab kätte helendava kera, mida saab parema või vasaku hiireklahviga vastavale poole visata. Visates, peale pööramist, kera käivitub, pimestades seda nägevad vastaseid lühikeseks ajaks ja selle poole seljaga olevad inimesi veidi vähemaks ajaks. \nE - Hot Hands: Võtab kätte tulekera, mis visates aktiveerub, luues tuleala, mis kahjustab selle sees olevaid mängijaid. Tules seistes saab Phoenix ennast veidi ravida. \nC - Blaze moodustab tulest seina, millest pole läbi näha ja mille sees seistes saab Phoenix ennast veidi ravida. \nX - Run It Back: Loob taassünnipunkti, peale mida võib Phoenix ära surra ja siis valitud punktis uuesti ellu ärgata.',
    'Raze': 'Raze: \nRoll: Duelist \nVõimed: \nQ - Blast Pack: Raze viskab põrkepaki, mis plahvatades viskab teda ja lähedal asuvaid mängijaid. \nE - Paint Shells: Raze viskab käsigranaadi, mis plahvatades tekitab lõhkemistsooni ja kahjustab vaenlasi. \nC - Boom Bot: Raze käivitab roboti, mis liigub ettepoole, otsides vaenlasi ja plahvatades nende läheduses. \nX - Showstopper: Raze võtab välja raketipilduja, mis laseb tugeva raketiga, tekitades suure plahvatuse antud piirkonnas ja tappes kõik selles piirkonnas olevad mängijad.',
    'Reyna': 'Reyna: \nRoll: Duelist \nVõimed: \nPassive: Kui vastane, kelle tappis Reyna või kes sai vigastada Reyna poolt, sureb, ilmub kera. \nQ - Devour: Kera annab Reynale elusid juurde. Kui Reyna on kasutanud oma x võimet, toimub see automaatselt. \nE - Dismiss: Kera muudab Reyna veidikeseks ajaks surematuks ja saab aidata Reynal teise kohta liikuda. Kui Reyna on kasutanud oma x võimet, muudab see Reyna ka nähtamatuks. \nC - Leer: Reyna võtab kätte palli, mis visates jääb sihitud kohta hõljuma ja vähendab kõigi vastaste, kes seda näevad, vaate- ja kuulmisvälja. \nX - Empress: Reyna tulistamiskiirus ja laadimiskiirus suurenevad, võime kestus uueneb iga Reyna poolt tapetud mängijaga.',
    'Sage': 'Sage: \nRoll: Sentinel \nVõimed: \nQ - Slow Orb: Võtab kätte aeglustava kera, mis peale viskamist maaga kokkupuutel moodustab aeglustava ala, milles olevad inimesed liiguvad aeglaselt. \nE - Healing Orb: Võtab kätte raviva kera, millega saab parempoolse klikiga ennast ravida ja mis vasakpoolse klikiga ravib tiimikaaslast, kelle poole on hiir suunatud. \nC - Barrier Orb: Võtab kätte kera, mida parema klikiga saab keerata ja vasaku klikiga saab asetada valitud kohta seina, millest ei saa läbi minna ega tulistada. Seina on võimalik ära lõhkuda \nX - Resurrection: Võtab kätte elluäratamise võime, millega saab enda kõrval oleva surnud tiimikaaslase uuesti ellu äratada.',
    'Skye': 'Sova: \nRoll: Initiator \nVõimed: \nQ - Trailblazer: Skye asub juhtima tiigrit, kes saab mõnda aega ringi liikuda ja kedagi hammustada, aeglustades pihta saanud tegelaste liikumist, sihtimist ja tulistamist. \nE - Quiding Light: Skye võtab kätte linnu, kelle lennuteekonda ta saab juhtida ja valida sobiva plahvatushetke, mil kõik, keda lind näeb, veidikeseks ajaks pimestatakse. \nC - Regrowth: Skye loob enda ümber raviva keskkonna, kus sees tiimikaaslased, keda Skye näeb saavad kaotatud elupunkte tagasi. \nX - Seekers: Skye võtab kätte kolm vaenlaseid otsivat olendit, kes liiguvad lähimate vastaste poole. Nendeni jõudes muutub vastase vaate- ja kuulmisväli väiksemaks.',
    'Sova': 'Sova: \nRoll: Initiator \nVõimed: \nQ - Shock Bolt: Võtab kätte vibu, millel on laenguga nool. Vibu saab vinna tõmmata vasaku hiirenupuga ja nupp lahti lastes läheb nool lendu. Noolele saab parema hiireklikiga kuni kaks põrget juurde lisada. Nool teeb tabamispiirkonnas vastastele haiget. \nE - Recon bolt: Võtab kätte vibu, millel on nool, mis maandudes laseb välja kaks vastaste asukohta avaldavat pulssi, mis tuvastavad vastaseid, keda nool otse näha suudab. Noolele saab parema hiireklikiga kuni kaks põrget juurde lisada. \nC - Owl Drone: Lennutab drooni, millega saab ringi vaadata ilma ennast ohtu seadmata ja mis saab lasta välja noole, mis kui vastast tabab, avaldab vastase asukoha kaks korda paari sekundi jooksul. \nX - Hunter’s Fury: Võtab kätte vibu, mis on laetud kolme pika seinu läbiva noolega.',
    'Viper': 'Viper: \nRoll: Controller \nVõimed: \nQ - Poison Cloud: Võtab kätte gaasiseadme, mille saab visata vabalt valitud kohta, ning see jääb püsima kogu raundi vältel. Võime kasutamiseks kulub kütust. Võimet saab uuesti kasutada rohkem kui üks kord ja selle saab üles korjata, et uuesti paigaldada. \nE - Toxic Screen: Võtab kätte seadme, mis laseb välja mürgise suitsuseina, mis blokeerib vaatevälja. Võimet saab uuesti kasutada vastavalt kütusele. \nC - Snake Bite: Võtab kätte seadme, mis laseb välja mürgise aine, mis kahjustab selle sees olevaid mängijaid ja teeb nii, et selle sees viibinud mängijad saavad veidi aega vahetult peale kokkupuudet ainega kaks korda rohkem viga. \nX - Viper’s Pit: Loob suure mürgise ala, mis nõrgestab selles viibivaid mängijaid ja vähendab nende vaatevälja. Ala kestab, kuni Viper sellest pikemaks ajaks välja läheb.',
    'Yoru': 'Yoru: \nRoll: Duelist \nVõimed: \nQ - Blindside: Yoru võtab kätte palli, mis peale heitmist ja ühe kora põrkamist kõiki, kes seda näevad, pimestab. \nE - Gatecrash: Yoru võtab kätte portaali, mille ta saab parema klikiga statsionaarselt maha panna ja mille ta saab vasaku klikiga saata otse edasi. Yoru saab portaali asukohta teleportida või panna portaali asukoha teleportivat häält tegema, et vastaseid segadusse ajada. \nC - Fakeout: Yoru võtab kätte klooni iseendast, mille ta saab maha panna või kohe aktiveerida. Ta saab maha pandud klooni ka kaugemalt aktiveerida ja aktiveeritud kloon liigub otse edasi ning kui vastased seda tulistavad pimestab see neid. \nX - Dimensional Drift: Yoru paneb ette maski, mis teeb nii, et ta saab joosta veidi kiiremini, kuulid ei tee talle kahju ja vastased ei näe teda, kui just Yoru neile väga lähedal pole. Yoru ei saa oma maski kandes ka ise vastaseid tulistada. Yoru mask kestab kuni aeg saab läbi või kuni ta selle ise eest ära võtab. Yoru saab maski kandes ka oma muid võimeid kasutada.',
  };

  var descriptionText = agentDescriptions[agentName];

  var paragraph = document.createElement('p');
  paragraph.innerHTML = descriptionText.replace(/\n/g, '<br>'); // Convert line breaks to HTML breaks

  paragraph.classList.add('agent-kirjeldus');

  descriptionElement.innerHTML = ''; // Clear previous content
  descriptionElement.appendChild(paragraph);
}